// DO NOT EDIT THIS FILE
// AUTO GENERATED BY THE DATABASE CONFIG

module.exports = {
    "development": {
        "client": "better-sqlite3",
        "connection": {
            "filename": "/home/wes/localhost/express-base/data/expressbase.sqlite"
        },
        "useNullAsDefault": true,
        "timezone": "utc"
    },
    "staging": {
        "client": "better-sqlite3",
        "connection": {
            "filename": "/home/wes/localhost/express-base/data/expressbase.sqlite"
        },
        "useNullAsDefault": true,
        "timezone": "utc"
    },
    "production": {
        "client": "better-sqlite3",
        "connection": {
            "filename": "/home/wes/localhost/express-base/data/expressbase.sqlite"
        },
        "useNullAsDefault": true,
        "timezone": "utc"
    }
}